# Generated by Django 3.1.4 on 2020-12-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rModified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Modified_img')),
            ],
        ),
        migrations.DeleteModel(
            name='Modified',
        ),
    ]
