# Generated by Django 3.1.4 on 2020-12-25 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_auto_20201225_1418'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rModified',
            new_name='Modified',
        ),
    ]
