# Generated by Django 3.1.4 on 2020-12-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_auto_20201225_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modified',
            old_name='image',
            new_name='image_m',
        ),
        migrations.AddField(
            model_name='original',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
