# Generated by Django 3.1.4 on 2020-12-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_auto_20201225_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='original',
            name='url',
        ),
        migrations.AlterField(
            model_name='modified',
            name='image_m',
            field=models.FileField(upload_to='Modified_img'),
        ),
        migrations.AlterField(
            model_name='original',
            name='image',
            field=models.FileField(upload_to='Original_img'),
        ),
    ]
