# Generated by Django 3.1.4 on 2020-12-25 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0005_auto_20201225_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='original',
            name='title',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='original',
            name='image',
            field=models.ImageField(upload_to='Original_img/'),
        ),
    ]
