# Generated by Django 3.1.4 on 2020-12-25 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0006_auto_20201225_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='original',
            name='title',
        ),
    ]
