# Generated by Django 3.1.4 on 2020-12-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0007_remove_original_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original',
            name='image',
            field=models.ImageField(upload_to='Original_img'),
        ),
    ]
