# Generated by Django 3.1.4 on 2020-12-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0008_auto_20201226_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=400)),
            ],
        ),
    ]
