# Generated by Django 3.1.4 on 2020-12-25 22:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0009_originalurl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OriginalURL',
        ),
        migrations.AddField(
            model_name='original',
            name='image_url',
            field=models.URLField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
    ]
