# Generated by Django 3.1.4 on 2020-12-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0010_auto_20201226_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original',
            name='image',
            field=models.ImageField(blank=True, upload_to='Original_img'),
        ),
        migrations.AlterField(
            model_name='original',
            name='image_url',
            field=models.URLField(blank=True, max_length=400),
        ),
    ]
