# Generated by Django 3.1.4 on 2020-12-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0011_auto_20201226_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='original',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='original',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
